stages:
  data_cleaning:
    cmd: python3 src/data/data_cleaning.py
    deps:
      - data/raw/BankChurners.csv
      - src/data/data_cleaning.py
    outs: 
      - data/cleaned/bankchurners_cleaned.csv