stages:
  data_cleaning:
    cmd: python3 src/data/data_cleaning.py
    deps:
      - data/raw/BankChurners.csv
      - src/data/data_cleaning.py
    outs: 
      - data/cleaned/bankchurners_cleaned.csv

  data_preparation:
    cmd: python3 src/data/data_preparation.py
    params:
      - Data_Preparation.test_size
      - Data_Preparation.random_state
    deps:
      - data/cleaned/bankchurners_cleaned.csv
      - src/data/data_preparation.py
    outs:
      - data/interim/train.csv
      - data/interim/test.csv

  data_preprocessing:
    cmd: python3 src/features/data_preprocessing.py
    params:
      - Data_Preprocessing.smote_random_state
      - Data_Preprocessing.smote_k_neighbors
    deps:
      - data/interim/train.csv
      - data/interim/test.csv
      - src/features/data_preprocessing.py
    outs:
      - data/processed/train_trans.csv
      - data/processed/test_trans.csv
      - models/preprocessor.joblib

  train:
    cmd: python3 src/models/train.py
    params:
      - Train.XG_boost.random_state
      - Train.XG_boost.n_estimators
      - Train.XG_boost.learning_rate
      - Train.XG_boost.max_depth
      - Train.XG_boost.subsample
      - Train.XG_boost.colsample_bytree
    deps:
      - data/processed/train_trans.csv
      - src/models/train.py
    outs:
      - models/model.joblib

  evaluate:
    cmd: python3 src/models/evaluation.py
    deps:
      - models/model.joblib
      - data/processed/test_trans.csv
      - src/models/evaluation.py
    metrics:
      - metrics.json

