stages:
  data_cleaning:
    cmd: python3 src/data/data_cleaning.py
    deps:
      - data/raw/BankChurners.csv
      - src/data/data_cleaning.py
    outs: 
      - data/cleaned/bankchurners_cleaned.csv

  data_preparation:
    cmd: python3 src/data/data_preparation.py
    params:
      - Data_Preparation.test_size
      - Data_Preparation.random_state
    deps:
      - data/cleaned/bankchurners_cleaned.csv
      - src/data/data_preparation.py
    outs:
      - data/interim/train.csv
      - data/interim/test.csv